[project]
name = "mipt-homeworks-2025"
version = "0.1.0"
description = "MIPT homeworks from base to production service"
readme = "README.md"
license = {text = "Apache License 2.0"}
requires-python = "==3.13.*"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi>=0.124.4",
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "flakeheaven>=3.3.0",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "ruff>=0.14.0",
    "types-aiofiles>=25.1.0.20240311",
]
lint = [
    "flakeheaven>=3.3.0",
    "mypy>=1.18.2",
    "ruff>=0.14.0",
    "types-aiofiles>=25.1.0.20240311",
]
